---
- name: assert jenkins_admin_password is set
  fail:
    msg: jenkins_admin_password is required
  when: jenkins_admin_password is not defined

- name: assert jenkins_tls_cert is set
  fail:
    msg: jenkins_tls_cert is required
  when: jenkins_tls_cert is not defined

- name: assert jenkins_tls_key is set
  fail:
    msg: jenkins_tls_key is required
  when: jenkins_tls_key is not defined

- name: install additional OS packages
  apt: name={{ packages }} state=present
  vars:
    packages:
      - docker.io
      - openjdk-8-jdk
      - python3-dev
      - python3-pip

- name: install jenkins
  import_role:
    name: geerlingguy.jenkins
  vars:
    jenkins_plugins: "{{ jenkins_default_plugins + jenkins_additional_plugins }}"
    jenkins_plugin_timeout: 120

- name: install saml keystore
  copy:
    src: "{{ jenkins_saml_keystore_path }}"
    dest: "{{ jenkins_home }}/saml-key.jks"
    owner: jenkins
    group: jenkins
    mode: "0640"
  when: jenkins_saml_keystore_path is defined

- name: add jenkins to the docker group
  user:
    name: jenkins
    groups: docker
    state: present
    append: yes

- name: install pipenv
  pip:
    name: pipenv
    executable: pip3
    state: present
    umask: "0022"

- name: install configuration as code
  copy:
    content: "{{ jenkins_config }}"
    dest: "{{ jenkins_home }}/jenkins.yaml"  # default configuration-as-code location
    owner: jenkins
    group: jenkins
    mode: 0640
  notify: restart jenkins

- name: setup jenkins credentials for CLI tasks
  copy:
    dest: /root/jenkins.txt
    mode: "0640"
    content: |
      admin:{{ jenkins_admin_password }}

- name: cron to update plugins
  copy: dest=/etc/cron.daily/datagov-jenkins src=etc_cron.daily_datagov-jenkins mode=0755 owner=root group=root

- name: install nginx for ssl termination
  import_tasks: nginx.yml
