---
- name: install OS packages
  apt: name={{ packages }} state=present
  vars:
    packages:
      - nginx
      - ssl-cert

- name: remove default nginx site
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: install tls certificate
  copy: content={{ jenkins_tls_cert }} dest=/etc/ssl/certs/jenkins.crt owner=root group=root mode=0644

- name: install tls key
  copy: content={{ jenkins_tls_key }} dest=/etc/ssl/private/jenkins.key owner=root group=ssl-cert mode=0640

- name: install nginx jenkins site
  copy: src=etc_nginx_sites-available_jenkins.conf.j2 dest=/etc/nginx/sites-available/jenkins.conf mode=0644 owner=root group=root
  notify: reload nginx

- name: enable jenkins site
  file: src=/etc/nginx/sites-available/jenkins.conf dest=/etc/nginx/sites-enabled/jenkins.conf state=link
  notify: reload nginx

- name: enable nginx
  service: name=nginx enabled=yes state=started
