---
- name: restart jenkins
  service: name=jenkins state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart docker
  service: name=docker state=restarted
  when: molecule_test is not defined
