---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: jenkins-bionic
    image: ubuntu:bionic
    published_ports:
      - 8080/tcp
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        jenkins_admin_password: admin
verifier:
  name: testinfra
  lint:
    name: flake8
